### ISSUE TITLE
Can I use arctica?

### ISSUE THREAD

**Issue by stefbon** [ArcticaProject/nx-libs#1036]
Hi,

I'm very interested in using the arctica libraries to enable remote desktop (using nx). I'm working on a software project I've called OSNS (Open Secure Network Services) which provides secure connections to the desktop user (using the SSH transport, auth and connections), and DNSSD for automatic connect to available SSH services in the network. One of the things which is very standard is SFTP over SSH. Everu desktop user can now browse files on the available shared directories using SFTP and FUSE.
Other things I'm thinking of is forward remote sockets (to servers like CUPS and MySql) to the desktop machine using SSH forwarding, chat (text and/or video) over the local network with others (colleagues ?). And also thus making remote desktoip work using the NX technology. That would be great! See:

https://github.com/stefbon/OSNS
https://osns.net/

First can you explain how the forwarding of X over SSH works please. I'm an experienced programmer, and have been using nx before (FreeNX and NoMachine clients) but never really understood how it works. If you can explain or point me to documentation I can appreciate it very much.
I know the X server runs on the workstation, so as I understand it this socket it forwarded to the server using the "forwarded-streamlocal@openssh.com" extension or the builtin X11 channel. Now desktop applications (on the server) use the dedicated channel to connect to the X server (on the workstation). Is this correct?
Now where does NX/nxagent/arctica comes in?

Thanks in advance,
Stef Bon
the Netherlands

**Comment by Djelff** [comment]
Yes, you can use nx-libs from ArcticaProject. These libraries are currently fully compatible with !M 3.x

If you have used FreeNX and NXClient please take a look at this: https://github.com/dimbor-ru

This freenx-server work file with nx-libs from ArcticaProject.
But some features do not work yet, such as Shadow session.
NXClient and Remmina connects to the same server using the NX protocol.

OpenNX, the NXСlient replacement, also works with ArcticaProject's nx-libs.
See MySession.cpp and AsyncProcess.cpp for an understanding of the negotiation and startup protocol on the Client side.

**Comment by uli42** [comment]
Without NX an X client communicates with your local X server via port
6000 + display number (6000 for display 0, 6001 for display 1, ...).
Using Openssh X forwarding (ssh -X)  this traffic is tunneled through
the ssh connection. Nethertheless the X protocol is very sensitive to
network latency because many packets require an acknowledgement or
answer. That's where NX kicks in: it runs an additional X server on
the server (where the X clients connect to) side and forwards what's
necessary to the local X server. It uses several approaches to reduce
communication (compression, caching, zeroing unnecessary data, ...) to
be much less latency sensitive. That nxagetn communicates with an
nxproxy process that runs locally where your local X server is.

So you need to run the nxagent on the remote side and the nxproxy on
the local side. Those two communicate over an ssh tunneled port. Note
that -X is not required here.

You can find some simple scripts that setup a connection in the
testscripts subdir of the repo.

Uli

**Comment by stefbon** [comment]
Thanks a lot for the explanation. The second X server per client I did not know. 
I'm using my own SSH implementation. So it's not required to create a new secure transport between client and server, the existing SSH session can create a (dedicated) channel between client and server. What do nxproxy and nxagent need? nxproxy needs a socket it can connect to (that is not so hard), it get's an fd, which is tunneled/connected to nxagent how? Is it a sort of port forwarding, or "local unix socket (streamlocal)?"

**Comment by uli42** [comment]
The details of the session setup are quite awkward to remember.
Basically you connect nxproxy (local) and nxagent (remote) through an
ssh forwarded port. AFAIR there are two ways supported: let the
nxagent connect to a waiting nxproxy or let nxproxy connect to a
waiting nxagent.
NX can make use of additional "slave channels" (further forwarded
ports) to support stuff like sound, printing, usb (in theory, not
implemented), ...)

The local nxproxy will connect to the local X server (like any other X
client) through the unix socket /tmp/.X11-unix/X<displaynum). Remote X
clients will connect to the nxagent through such a socket on the
remote server. This is nothing special, this is plain X11 behaviour.

The session configuration is communicated from the nxproxy side to the
nxagent side with an options file that should be known on both sides.
So that has to be created before starting any of the nx* programs.

I think it is best to look at the mentioned example scripts or examine
a running session to get a better understanding of all that. It is
important to know that x2go sets up the session in different manner
than nomachine NX/FreeNX.

Note: In the early days of NX you needed to run nxproxy AND nxagent on
the remote side and nxproxy on the local side. nxproxy has been
integrated into nxagent long time ago so that's no longer required.
For a subset of NX optimizations you can even run a setup where both
sides only have an nxproxy running. However, I am not sure if that
setup supports reconnecting to a session or if you need to start a new
session everytime.

Uli

BTW: IF you dig into this it would be great if you could document the
session setup stuff. AFAIK we do not have a proper documentation of
all that. ;-)

**Comment by stefbon** [comment]
Thanks a lot! I will try what you suggest.
Maybe the use of a environment variable is required, simular like git does. It looks for the env. variables
GIT_SSH and GIT_SSH_COMMAND. See man git:ENVIRONMENT VARIABLES:other.

I will try this and report back. It I got this working it will provide a ready to use interface to a RDP using NX for desktop users in the network, if a server is in the network. Only required is that this server has to announce this via DNSSD (for example Avahi).
Have you thought about this? Thus announce something like _nx-ssh._tcp (simular to _sftp-ssh._tcp)?

Report soon,
Stef

**Comment by uli42** [comment]
No, this way beyond scope of nx-libs.

I also think stuff like that belongs to the framework (nomachine, freenx,
x2go) and not the underlying software. Furthermore, if I get your
concept right, you would like to start the session in disconnected mode and
inform possible clients via announcement. Unfortunately currently nx does
not support starting a session in detached mode...

**Comment by stefbon** [comment]
I do not know what you mean by "detached mode" or disonnected mode. I've said that advertisement via DNSSD of a NX server available in the network is a good thing in my opinion.
And second, I'm looking for a way to connect nxproxy with the remote nxagent using a custom ssh connection (which is already there). Something like (for nxproxy if using ssh) "create or use a SSH transport layer to server and get a dedicated channel/connection to nxagent on server" (and simular for sound and other services). I think that is not so hard.

**Comment by uli42** [comment]
On Thu, Jan 20, 2022 at 9:52 PM stefbon ***@***.***> wrote:
>
> I do not know what you mean by "detached mode" or disonnected mode. I've said that advertisement via DNSSD of a NX server available in the network is a good thing in my opinion.


Ah,ok, you just want to advertise the service. I was talking about
advertising sessions, that can be reconnected.
As nx-libs does not bring a "server" functionality this must be
implemented in the framework that takes care of the connection, e.g.
x2go or FreeNX.

> And second, I'm looking for a way to connect nxproxy with the remote nxagent using a custom ssh connection (which is already there). Something like (for nxproxy if using ssh) "create or use a SSH transport layer to server and get a dedicated channel/connection to nxagent on server" (and simular for sound and other services). I think that is not so hard.

1. determine a port number to forward via ssh
2. generate the options file of both the server (nxagent) side and the
client (nxproxy) side
3. run nxagent on the server side using the options file,
4. run nxproxy

This script shows how to setup a basic session:
https://github.com/ArcticaProject/nx-libs/blob/3.6.x/testscripts/run-nxproxy2nxagent-over-network.
If you have nxagent installed on your system just run it and do what
it tells you at the end, after that you have a running NX session.

However, this will be very basic and you'll have to add scripts to run
your desktop environment or terminal in that session. If you want to
be able to suspend and resume the session, you need to add further
logic (suspend is sending a SIGHUP to the nxagent process. Resume is
updating the options file and then sending a SIGHUP to nxagent and
starting a new nxproxy on the local side.

All in all you can of course implement that but it's probably much
easier to make use x2goclient/x2goserver. For the client side you can
also try the pyhoca-cli command line client. These are projects that
make use of nx-libs but are not part of Arctica/nx-libs. I think it
should work like this:
1. add a little service that advertises that the x2goserver software
is installed.
2. Somehow instruct the x2goclient (or pyhoca-cli) to use your ssh
connection. The easiest way to achieve that is probably by creating a
port forward (over your already existing ssh connection) to the remote
sshd and the instruct x2goclient to connect to localhost:<port> using
the built-in ssh. For this you might need to pre-configure sessions in
x2goclient (might be possible on the fly, I have no idea). Update: I
think using pyhoca-cli would be best as you can pass all required
parameters directly on the command line.

HTH.

Uli

**Comment by uli42** [comment]
No more answer. Feel free to re-open the issue if any further questions arise.
