### ISSUE TITLE
A question about nxagent shadow mode

### ISSUE THREAD

**Issue by dimbor-ru** [ArcticaProject/nx-libs#1048]
Hello!
We have contacted you once before about restoring FreeNX.
At the moment of development has already achieved a significant acceleration of the connection, not only with OpenNX, but also with NXClient's.
Also, the internal mechanisms have been redesigned, in particular the config to sqilite, and the handling of smb/cups connections has been significantly improved and stabilized. vnc and rdp over nx worked too.

But now I'm facing a problem with shadow session connections, once a long time ago it worked and worked great, but now I can't establish a shadow connection to the session. 
I can already select a session to shadow connect, but starting command like
"nxagent ... -S -shadow :4000 -shadowmode 1 ... :4001" causes the agent to start proxy in client mode, wait for a connection to its display, and time out. I don't see any error in logs to catch on. Experimenting with code here https://github.com/dimbor-ru/freenx-server/tree/shadow_sessions 

I would like to know if this protocol works in the current version of arctic, and if there are examples for such connections.
Thank you in advance.

**Comment by dimbor-ru** [comment]
I am sorry. It was a false alarm. My problems were caused by confusion with freenx startup parameters. I have no claims to the Arctic.

**Comment by sunweaver** [comment]
@dimbor-ru Ack. Thanks for getting back to us on this. We tried and always try to keep API interface for FreeNX as it used to be.

**Comment by uli42** [comment]
Shadow sessions are kind of an unloved child, because they are slow by
design. So I have not tested that for quite some time. However, I am pretty
sure we had people having questions about the desktop size in shadowed
mode, so I _think_ it works generally. IIRC I have debugged some color
problems in 32bit shadow sessions some years ago.

I suggest to test shadowing with a current NX in an x2go setup and check if
it works.

Maybe FreeNX is doing a different way of setting up shadow sessions that is
broken while the one x2go is using works. I don't know for sure, though.

Uli


dimbor-ru ***@***.***> schrieb am Sa., 11. Juni 2022, 16:09:
