### ISSUE TITLE
packaging libX11 

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#233]
```
$ rpm -qlp ~/rpmbuild/RPMS/x86_64/nxagent-3.5.99.1-0.0build1.el6.x86_64.rpm -v
...
drwxr-xr-x    2 root    root                        0 Sep 29 20:59 /usr/lib64/nx-X11
lrwxrwxrwx    1 root    root                       15 Sep 29 20:59 /usr/lib64/nx-X11/libX11.so -> ../libNX_X11.so
lrwxrwxrwx    1 root    root                       19 Sep 29 20:59 /usr/lib64/nx-X11/libX11.so.6.2 -> ../libNX_X11.so.6.2
...
```

These links should be part of the libNX_11 package, not of the nxagent package.

**Comment by sunweaver** [comment]
I don't agree on this (i.e. #233).

These special symlinks are not part of the libNX_X11 library, but part of our nasty LD_LIBRARY_PATH (or later on RPATH) hack for nxagent. That's why I included them in nxagent packaging. Debian's lintian tool will, furthermore, complain if a shared library packages contains more files than the actual shared library and closely related files.

**Comment by uli42** [comment]
Ok, I just wanted to point out that it looks wrong at first sight.

OTOH what else are those links than "closely related files"?

**Comment by sunweaver** [comment]
On  Mi 19 Okt 2016 09:03:47 CEST, Ulrich Sibiller wrote:

> Ok, I just wanted to point out that it looks wrong at first sight.
> 
> OTOH what else are those links than "closely related files"?

They are simply not closely related enough for lintian (closely  
related: libNX_X11.so symlink, pkg-config files, etc.).

## Mike

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by sunweaver** [comment]
Closing this issue, nothing to be changed.
