### ISSUE TITLE
add libX11 links

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#234]
For testing it would help if there were `libX11` links in addition to the `libNX_X11` links in exports/lib after compilation. However, I cannot seem to find out how to instruct Imake for that...

```
$ ls -l exports/lib/
insgesamt 0
lrwxrwxrwx 1 usibill sundc 26 18. Okt 11:13 libNX_X11.so -> ../../lib/X11/libNX_X11.so*
lrwxrwxrwx 1 usibill sundc 28 18. Okt 11:13 libNX_X11.so.6 -> ../../lib/X11/libNX_X11.so.6*
lrwxrwxrwx 1 usibill sundc 30 18. Okt 11:13 libNX_X11.so.6.2 -> ../../lib/X11/libNX_X11.so.6.2*
```

Also, linking `libXcomp*` to that dir as well would help even more.

**Comment by sunweaver** [comment]
[...] (comment removed as it was placed here erroneously...

**Comment by sunweaver** [comment]
sorry, comment was for #233... Putting it there...

**Comment by sunweaver** [comment]
@uli42: When doing it the imake way, I guess this has to go into nx-X11/config/cf/lnxLib.rules (line 147 ff.). But would it also be acceptable to hack that into our main Makefile (somewhere below line  70)?

**Comment by sunweaver** [comment]
... just saw, that you have the "fixes" statement in the commit msg... Ignore the that part of my noise.

**Comment by uli42** [comment]
So why did you reopen this issue?

Is it because of this?: "Also, linking libXcomp\* to that dir as well would help even more."

**Comment by sunweaver** [comment]
On  Sa 29 Okt 2016 14:52:10 CEST, Ulrich Sibiller wrote:

> So why did you reopen this issue?
> 
> Is it because of this?: "Also, linking libXcomp\* to that dir as well  
> would help even more."

Simply, because I erroneously clicked on "Comment & Close", instead of  
"Comment"...

Ignore the close-reopen-flaw.

## Mike

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by uli42** [comment]
What do you think about linking libXcomp\* to exports/lib, too?

**Comment by sunweaver** [comment]
On  Sa 29 Okt 2016 15:01:37 CEST, Ulrich Sibiller wrote:

> What do you think about linking libXcomp\* to exports/lib, too?

If exports/lib is only used at build time / for testing, then yes.

IIRC, exports/lib gets used at build time, whereas .build-exports/ is  
the template for make install, right?

If so, we should make sure that what we put in exports/ does not end  
up in .build-exports/.

At the moment, after build I have a copy of  
.build-exports/include/nx-X11 in .build-exports/include/X11. This has  
been caused by one of your recent changes I guess. Do you agree that  
we should get rid of that copy-of-code in .build-exports/include/X11  
again? What you need is symlinking magic in exports/, right?

## Mike

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de
