### ISSUE TITLE
why own rgb file?

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#259]
Why do we have an own `etc/rgb` file? It is identical to the `/usr/share/X11/rgb.txt` (on ubuntu 14.04) and that file should be existing on all systems offering an Xorg installation.

**Comment by sunweaver** [comment]
On  So 30 Okt 2016 13:49:09 CET, Ulrich Sibiller wrote:

> Why do we have an own `etc/rgb` file? It is identical to the  
> `/usr/share/X11/rgb.txt` (on ubuntu 14.04) and that file should be  
> existing on all systems offering an Xorg installation.

I agree on this. When removing that file, make sure that nxagent  
depends on x11-common (Debian) and ??? (RPM based systems).

## Mike

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by Ionic** [comment]
Wait, haven't newer X.Org versions dropped the rbg.txt file completely?

**Comment by sunweaver** [comment]
@Ionic: x11-common 1:7.7+16 still has it. Where did you get that information from?

**Comment by Ionic** [comment]
Maybe I'm confusing something here. In earlier versions, X.Org shipped a file called `rgb` in `/etc/X11`, while later versions switched to `/usr/share/.../rgb.txt`.

It was probably never dropped, but I remember having had problems due to the rgb file not being found or something like that in the past. What probably **was** removed is the explicit configuration of the file path in a standard `X.org.conf` file (although X.Org nowadays prefers to start the server without any configuration file in the first place and rely on autodetection if possible, IIRC.)

**Comment by Ionic** [comment]
This said, if we remove it from `nx-libs` and don't ship a private copy, we'll need to make sure that the system file is being loaded and adapt the code for that. Just dropping the file without further work will probably lead to programs failing to start because they were unable to find the color `Black` or other stuff.

**Comment by sunweaver** [comment]
Yeah, sure. Also we need to check other distros, installation paths of that file, etc.

I mark this issue for milestone 3.7.x, with 3.6.x we keep our own copy for now.

**Comment by uli42** [comment]
Has been addressed in #319

**Comment by sunweaver** [comment]
Reopening, as it has not yet been solved. @Ionic will work on the #319 review this week and the commit in there closes this bug then.
