### ISSUE TITLE
Unused files in libX11 build

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#265]
These files are currently unused in the libX11 build. Check, if Imakefile is incomplete here.

```
./nx-X11/lib/X11:
-rw-rw-r-- 1 uli uli     2317 Okt 29 21:27 lcDynamic.c 
-rw-rw-r-- 1 uli uli     3595 Okt 29 21:27 XlcSL.c
-rw-rw-r-- 1 uli uli     1814 Okt 29 21:27 Xaixlcint.h
-rw-rw-r-- 1 uli uli    15503 Okt 29 21:27 XlcDL.c
-rw-rw-r-- 1 uli uli     6343 Okt 29 21:27 UIThrStubs.c
-rw-rw-r-- 1 uli uli    11611 Okt 29 21:27 XDefaultIMIF.c
-rw-rw-r-- 1 uli uli    26909 Okt 29 21:27 XDefaultOMIF.c

./nx-X11/lib/X11/lcUniConv:
-rw-rw-r-- 1 uli uli  31002 Okt 29 21:27 cjk_tab_to_h.c
-rw-rw-r-- 1 uli uli  16887 Okt 29 21:27 8bit_tab_to_h.c
-rw-rw-r-- 1 uli uli    358 Okt 29 21:27 ascii.h
```

**Comment by sunweaver** [comment]
@uli42: looking into this now.

The file

  * lcDynamic.[co]

is missing in libNX_X11's Imakefile, so I added that under LCSRCS/LCOBJS.

The files

  * XlcSL.[co]
  * XlcDL.[co]
  * XDefaultIMIF.[co]
  * XDefaultOMIF.[co]

do not get built, because there is a variable naming issue in libNX_X11's Imakefile. About to fix that.

The Xaixlcint.h will be handled by PR #289, so ignoring it here.

The files

  * 8bit_tab_to_h.c
  * cjk_tab_to_h.c

exist for documentation purposes, see the new doc/libNX_X11/lcUniCOnv/README. I will move over those files to nx-libs' doc/libNX_X11/ folder, too.

The file UIThrStubs.c seems to be needed on old FreeBSDArchitectures and OpenBSDArchitecture. So it should be removed, if we decide dropping support for those. But not now.

  * ascii.h

is not included by lcUTF8.c (it is ifdef'ed out). So I drop this.

**Comment by sunweaver** [comment]
The files...

  *  lcDynamic.[co]
  *  XlcSL.[co]
  *  XlcDL.[co]
  *  XDefaultIMIF.[co]
  *  XDefaultOMIF.[co]

are actually for building loadable i18n module support, which never was present in nxagent's libNX_X11.

So dropping that entirely, opposing what I said above.
