### ISSUE TITLE
move nxcompext into nx-X11/programs/Xserver/

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/nx-libs#276]
I just noticed that nxcompext includes (Xserver-only, private) headers from nx-X11/programs/Xserver/include/. As a shared library this is nothing it should do.

My suggestion is: moooooveeee nxcompext into nx-X11/programs/Xserver/.

**Comment by sunweaver** [comment]
... I stumbled across this, because currently our builds fail in clean chroot envs...
https://jenkins.arctica-project.org/job/nx-libs.deb+nightly/138/

**Comment by uli42** [comment]
insert `#undef _XSERVER64` at the top of xcompext.c and it works!

**Comment by sunweaver** [comment]
Hi Uli,

On  Do 03 Nov 2016 02:03:59 CET, Ulrich Sibiller wrote:

> insert `#undef _XSERVER64` at the top of xcompext.c and it works!

I fear that simply undeffing _XSERVER64 is no generic solution. I now  
moved the nxcompext code directly into Xserver/hw/nxagent. The file  
xcompext.c is not CompExt.c, all other files have been copied, except  
Colormap.[ch] from nxcompext. These files are now named  
ColormapComp.[ch].

I Xserver/hw/nxagent/CompExt.c, I added `#include "Agent.h"`,  
because I believe that it is that, what we need to do (instead of  
undeffing _XSERVER64). However, this does not work right away. My  
sense is, that we have to prefix several Xlib entities with "Xlib"  
(e.g. XlibDisplay, XlibWindow, etc.).

@Ionic: you encoutered problems with nxcompext code in nxagent  
earlier. Any idea on this?

## Mike

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by uli42** [comment]
It was late... My combination consists of undef + Agent.h

Why don't you put xcompext into a subdir an leave the names?

Vom Smartphone gesendet.

----- Ursprüngliche Nachricht -----
Von: "Mike Gabriel" notifications@github.com
Gesendet: ‎03.‎11.‎2016 09:43
An: "ArcticaProject/nx-libs" nx-libs@noreply.github.com
Cc: "Ulrich Sibiller" uli42@gmx.de; "Comment" comment@noreply.github.com
Betreff: Re: [ArcticaProject/nx-libs] move nxcompext intonx-X11/programs/Xserver/ (#276)

Hi Uli,

On Do 03 Nov 2016 02:03:59 CET, Ulrich Sibiller wrote:

> insert `#undef _XSERVER64` at the top of xcompext.c and it works!

I fear that simply undeffing _XSERVER64 is no generic solution. I now 
moved the nxcompext code directly into Xserver/hw/nxagent. The file 
xcompext.c is not CompExt.c, all other files have been copied, except 
Colormap.[ch] from nxcompext. These files are now named 
ColormapComp.[ch].

I Xserver/hw/nxagent/CompExt.c, I added `#include "Agent.h"`, 
because I believe that it is that, what we need to do (instead of 
undeffing _XSERVER64). However, this does not work right away. My 
sense is, that we have to prefix several Xlib entities with "Xlib" 
(e.g. XlibDisplay, XlibWindow, etc.).

@Ionic: you encoutered problems with nxcompext code in nxagent 
earlier. Any idea on this?

## Mike

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22 0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de
