### ISSUE TITLE
JPEG Compression: Research on using native turbojpeg API instead of libjpeg API

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/nx-libs#351]
nxagent uses libjpeg API (IJG) currently. We should investigate switching over to the native turbojpeg API instead and see if we can get a performance boost out of that.

**Comment by Ionic** [comment]
Yes, we should just switch to `libjpeg-turbo`. It's a drop-in replacement as far as we're concerned and any performance improvement is great, since it essentially comes for free. We went through the pro and cons in MacPorts years ago and the general consensus (minus one user, who SWORE he could could make out a file that was decoded by IJG Jpeg vs. `libjpeg-turbo`...) was that `libjpeg-turbo` is just as good as IJG Jpeg.

For `nx-libs`, it's merely a matter of changing dependencies.

**Comment by Ionic** [comment]
Err, ignore my comment, you were actually talking about the API itself and I just remembered that Debian switched to using `libjpeg-turbo` by default some years ago...

**Comment by sunweaver** [comment]
It seems that the TURBOjpeg API wraps around the libjpeg-turbo API (taken from this [1] document). So no need to do an API switch in nxagent. The distro decides and most distros (also Debian) have switched over already.

[1] http://www.libjpeg-turbo.org/About/TurboJPEG
