### ISSUE TITLE
FTBFS on Fedora 25

### ISSUE THREAD

**Issue by mikedep333** [ArcticaProject/nx-libs#459]
150cbc2 (the current version on the 3.6.x branch) is failing to build on Fedora 25.

I am using our upstream .spec file in Mock.

See this Mock [build.log](https://pastebin.com/agj5jFgT)

**Comment by mikedep333** [comment]
Similar errors in the [build.log](https://pastebin.com/3PiEyAxj) on epel7.

**Comment by mikedep333** [comment]
Similar errors in the [build.log](https://pastebin.com/1RjZqN5a) on epel6.

**Comment by mikedep333** [comment]
I just found this line:
./mesa-quilt: line 32: quilt: command not found

I will submit a PR to add quilt to the spec file. EPEL, Fedora, and SUSE all have it.

**Comment by uli42** [comment]
There's an open issue regarding this. I don't want epel requirements because I faced dependecy problems several times. I would prefer dropping quilt. This also leads to problems when switching branches...

Uli

Vom Smartphone gesendet.

----- Ursprüngliche Nachricht -----
Von: "Mike DePaulo" <notifications@github.com>
Gesendet: ‎25.‎05.‎2017 04:18
An: "ArcticaProject/nx-libs" <nx-libs@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: Re: [ArcticaProject/nx-libs] FTBFS on Fedora 25 (#459)

I just found this line:
./mesa-quilt: line 32: quilt: command not found
I will submit a patch to add quilt to the spec file. EPEL, Fedora, and SUSE all have it.

**Comment by uli42** [comment]
See issue #444

**Comment by sunweaver** [comment]
uli42: we won't drop quilt because it makes the nx-specific patch management very easy during  development. We simply need a different approach for applying patches for Mesa, if quilt is not available.

**Comment by uli42** [comment]
On Wed, May 31, 2017 at 1:13 PM, Mike Gabriel <notifications@github.com> wrote:
>
> uli42: we won't drop quilt because it makes the nx-specific patch management very easy during development. We simply need a different approach for applying patches for Mesa, if quilt is not available.


What patches do you mean? I am only aware of patches in the debian dir
and the mesa dir. We can use quilt for debian, I think it will be easy
to add a dependency there. But for Redhat/Cetnos/Fedora/Suse quilt is
not in the distribution and should therefore not be required.

**Comment by sunweaver** [comment]
Funnily, commit 26c371b80cea388207cba3e8741240ff2837818b did not close this issue report. Doing it manually now.
