### ISSUE TITLE
drop options in DISPLAY?

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#564]
I'am wondering if we should drop "options via DISPLAY variable" and stick to an options file (passed via '-options' for nxagent and via `options=file` for nxproxy) only. 

I _suppose_ this is originating from dxcp and should not be required with nxproxy and nxagent.
I have not checked how that fits in with nxcomp's option handling but it would make it clearer how nxagent and nxproxy are supposed to be used and where options have to be provided.

I am getting confused myself regurlarly...

**Comment by Ionic** [comment]
X2Go has historically always passed options (for nxagent) via `DISPLAY`. Disallowing this would make it break in a horrible fashion.

It's been a mixed deal, though, since while a common set of options were passed via `DISPLAY`, it's only really ever passing `nx/nx,options=FILE:DISPLAYNO`; thus really only an indirect reference to a file containing more options. Provided that this also works via `-option(s)` on the command line, changing it wouldn't be too difficult, but I'm not sure how older versions cope with option string vs. option file (and whether references are handled correctly or crash and burn.)

**Comment by sunweaver** [comment]
I also think that we should leave this in, as it changes the "API" of nxagent/nxproxy tremendously.

Thus, closing...
