### ISSUE TITLE
Loop.cpp: Logging is buggy

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#577]
If nxproxy is used with `-d 4` but without `-o` all logging happens on stderr. Some lines are missing then:

```
INFO  Loop.cpp/handleCheckSelectInLoop:14016 Loop: Maximum descriptors is [9] at 00:19:27:656.170.
INFO  Loop.cpp/handleCheckSelectInLoop:14040 .
INFO  Loop.cpp/handleCheckSelectInLoop:14067 [none].
INFO  Loop.cpp/handleCheckSelectInLoop:14071 Loop: Select timeout is 5 S and 0 Ms.
```

The corresponding code is shown below. The output generated in lines 14026 and 14049 is  missing completely. 

```
  14016   nxinfo << "Loop: Maximum descriptors is ["
  14017          << setFDs << "] at " << strMsTimestamp()
  14018          << ".\n" << std::flush;
  14019 
  14020   int i;
  14021 
  14022   if (setFDs > 0)
  14023   {
  14024     i = 0;
  14025 
  14026     nxinfo << "Loop: Selected for read are ";
  14027 
  14028     for (int j = 0; j < setFDs; j++)
  14029     {
  14030       if (FD_ISSET(j, &readSet))
  14031       {
  14032         nxinfo << "[" << j << "]" << std::flush;
  14033 
  14034         i++;
  14035       }
  14036     }
  14037 
  14038     if (i > 0)
  14039     {
  14040       nxinfo << ".\n" << std::flush;
  14041     }
  14042     else
  14043     {
  14044       nxinfo << "[none].\n" << std::flush;
  14045     }
  14046 
  14047     i = 0;
  14048 
  14049     nxinfo << "Loop: Selected for write are ";
  14050 
  14051     for (int j = 0; j < setFDs; j++)
  14052     {
  14053       if (FD_ISSET(j, &writeSet))
  14054       {
  14055         nxinfo << "[" << j << "]" << std::flush;
  14056 
  14057         i++;
  14058       }
  14059     }
  14060 
  14061     if (i > 0)
  14062     {
  14063       nxinfo << ".\n" << std::flush;
  14064     }
  14065     else
  14066     {
  14067       nxinfo << "[none].\n" << std::flush;
  14068     }
  14069   }
  14070 
  14071   nxinfo << "Loop: Select timeout is "
  14072          << selectTs.tv_sec << " S and "
  14073          << (double) selectTs.tv_usec / 1000
  14074          << " Ms.\n" << std::flush;
```

**Comment by Ionic** [comment]
The problem is that I intended this behavior. Well, not quite, but fixing this isn't really possible.

Consider this:
  * a log line is being constructed
  * signal handler interrupts this operation by logging itself (which is normally not allowed anyway, since signal handlers are only meant to execute one atomic task [e.g., update a single integer in one instruction] and then terminate - but let's look at NX code and have a laugh at this, since there are signal handlers actually logging stuff, c.f., `HandleSignal`)
    * new entry in queue is created for the logging operation within the signal handler
    * data gets appended to this new entry
    * finally written out

If I insert a step to flush the other data out before creating a new queue entry, we'd delete the previous, original entry  and THAT will lead to a crash after the signal handler executed  since it would be trying to append data to something that doesn't exist any longer on resumption of the code that was interrupted.

The current implementation avoids this problem, but creates the problem you mentioned here.

The actual issue is that we cannot really know when an operation is done - so far, we assume that flushing is possible if either `std::flush` have been used, the string exceeds a given length or a newline is contained in the logging string. Since these are missing in the example provided above, the messages just won't be printed but stored indefinitely.

**Comment by uli42** [comment]
Well, then the mentioned part is doing something that the logging code does not support (yet).

Would it help if we Introduce a second logging method LogPartial() where a unique number is passed? All messages with that number are considered as belonging together and are printed only when LogPartialEnd() ist called. This would change the order in case of signal handlers coming inbetween but it would at least ensure we do not lose information.

Or another approach: On entry the signal handler flushes the queue but in a different fashion: Elements are not removed from the queue but only marked. The next flush outside the handler will then finally remove those queue elements.

Or, thinking further, maybe it would help if the signal handler logs a linefeed before logging its own stuff.

In the case we have here we could also change the code to build the string to be logged itself and then only call the logging code once.

**Comment by Ionic** [comment]
I've implemented a way to append to a logging line in the mentioned commit that closed the message.

Generally, the new `nx*_append` macros can be used to append to a log line, but there are a few caveats to this:
  - `nx*_append` must directly follow a previous `nx*` or `nx*_append` call, with the log level `*` matching (e.g., `nxinfo << ...; nxinfo_append << ...; nxinfo_append << ...;` works, but `nxinfo << ...; nxinfo_append << ...; nxdbg_append << ...;` or a plain `nxdbg_append << ...; nxdbg_append << ...;` without a previous `nxdbg << ...` call won't)
  - `nx*_append` must **not** be used with strings containing newline characters, a flush operator or be longer than `1024` bytes (which is a problem on its own, but there's no easy way to fix that), **unless** no other `nx*_append` calls follow (e.g., `nxinfo << ...; nxinfo_append << "foo " << "bar "; nxinfo_append << "baz" << std::flush;` works, but `nxinfo << ...; nxinfo_append << "foo\n"; nxinfo_append << "bar " << "baz" << std::flush;` won't)
  - for an append to work, the original `nx*` line must not contain a newline, a flush operator or be longer than `1024` bytes (e.g,. `nxinfo << ...; nxinfo_append << ...;` works, but `nxinfo << "...\n"; nxinfo_append << ...;` or `nxinfo << ... << std::flush; nxinfo_append << ...;` won't)

The limitations are unfortunate, but really limitations of streams and the way we flush the queue.
