### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by mjtrangoni** [ArcticaProject/nx-libs#622]
Hi,

I think this could add some value to the project, building **automatically** against some different compilers and different compiler versions too!  See for example, [Travis C++](https://docs.travis-ci.com/user/languages/cpp/).

If you agree, I would like to collaborate with this implementation.

**Comment by sunweaver** [comment]
Hi Mario,

On  Fr 29 Dez 2017 11:46:29 CET, Mario Trangoni wrote:

> Hi,
>
> I think this could add some value to the project, building  
> **automatically** against some different compilers and different  
> compiler versions too!  See for example, [Travis  
> C++](https://docs.travis-ci.com/user/languages/cpp/).
>
> If you agree, I would like to collaborate with this implementation.

we already do some package builds on .deb based systems under  
jenkins.arctica-project.org.

However, this is far from a versatile Travis CI setup. So, if you  
volunteer in settings something up around this, please go ahead and  
file PRs, so that we integrate the travis configuration you come up  
with.

Thanks for joining in!!!
Mike

PS: maybe you want to share in what context you use nx-libs / nxagent. Thanks!
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by Ionic** [comment]
> we already do some package builds on .deb based systems under jenkins.arctica-project.org.

And, more recently, via the X2Go build infrastructure, that also includes RPM-based platforms.

**Comment by mjtrangoni** [comment]
Hi @sunweaver @Ionic,

Well I use the `nx-libs` that @uli42 provides, and I told him I can collaborate with the project too. 

About the many build infrastructures, what do you think about adding or documenting them in a GitHub wiki-page [here](https://github.com/ArcticaProject/nx-libs/wiki)? By the way, I think the `README.md` file should be a bit shorter too, linking the extended documentation to the wiki.

As well as the building topic, there is an option called [Projects](https://github.com/ArcticaProject/nx-libs/projects) where you can link all the open and closed issues related or expected for a release.

Thank you!

**Comment by mjtrangoni** [comment]
Travis is working now.
