### ISSUE TITLE
Patch to add version info to nxagent -help

### ISSUE THREAD

**Issue by realsimix** [ArcticaProject/nx-libs#653]
Attached small patch adds the version info to the output of nxagent -help:

```
$ nxagent -help 2>&1 | head -n 8
NXAGENT - Version 3.5.99.13

Usage: nxagent [<options>] [:<display>]
-a #                   mouse acceleration (pixels)
-ac                    disable access control restrictions
-audit int             set audit trail level
-auth file             select authorization file
bc                     enable bug compatibility
```
Would be nice if this could be added.
[nx-libs-3.6.x-20180124-nxagent_version.patch.txt](https://github.com/ArcticaProject/nx-libs/files/1663441/nx-libs-3.6.x-20180124-nxagent_version.patch.txt)

**Comment by uli42** [comment]
Thank you! This also fixes #639.

However, why are you adding 
```
+#define NXAGENT_VERSION_STRING NX_VERSION_CURRENT_STRING
```
instead of simply using `NX_VERSION_CURRENT_STRING` directly?

Also, please have a look at `checkX2goAgent` in `hw/nxagent/Init.c`. The help should also consider this check. 

Please enclose your changes in `#ifdef NXAGENT_SERVER`. This simplyfies backports.

Finally while your are working at that it would be great if you could have a look at #606

**Comment by realsimix** [comment]
Thanks for your input!

I tried to improve it as suggested. Can you have a look at it now?
[nx-libs-3.6.x-20180124-nxagent_version.patch.txt](https://github.com/ArcticaProject/nx-libs/files/1664483/nx-libs-3.6.x-20180124-nxagent_version.patch.txt)

**Comment by realsimix** [comment]
While rethinking it, I'll create another version with nxagent -V to print version info.

**Comment by realsimix** [comment]
Attached patch does it:
```
$ nxagent -help
Usage: nxagent [<options>] [:<display>]

-a #                   mouse acceleration (pixels)
-ac                    disable access control restrictions
-audit int             set audit trail level
-auth file             select authorization file
...
-S                     enable shadow mode
-B                     enable proxy binding mode
-V                     print version information
-options file          file containing nx/nx options
```
```
$ nxagent -V
NXAGENT - Version 3.5.99.13
```
Tries to be consistent with nxproxy which uses `nxproxy -v`, manpage is also updated.
[nx-libs-3.6.x-20180124-nxagent_version.patch.txt](https://github.com/ArcticaProject/nx-libs/files/1666881/nx-libs-3.6.x-20180124-nxagent_version.patch.txt)

**Comment by realsimix** [comment]
Just a minor update because not all compilers liked it.
[nx-libs-3.6.x-20180124-nxagent_version.patch.txt](https://github.com/ArcticaProject/nx-libs/files/1667133/nx-libs-3.6.x-20180124-nxagent_version.patch.txt)

**Comment by uli42** [comment]
Hi Simon,

sorry for being naggy, but as nxagent is derived from Xorg we want to
stay as close as possible option-wise (this makes it easier to
backport/upgrade). The X server on my Centos7 has a -version option.
We should better adapt this instead of adding anther option. Besides,
the capital letter options are selecting a mode nxagent should run in,
so -V does not really fit in there...:

$ Xorg -version

X.Org X Server 1.19.3
Release Date: 2017-03-15
X Protocol Version 11, Revision 0
Build Operating System:  3.10.0-514.16.1.el7.x86_64
Current Operating System: Linux anubis 3.10.0-693.11.6.el7.x86_64 #1
SMP Thu Jan 4 01:06:37 UTC 2018 x86_64
Kernel command line: BOOT_IMAGE=/vmlinuz-3.10.0-693.11.6.el7.x86_64
root=/dev/mapper/vg0-root ro crashkernel=auto rd.lvm.lv=vg0/root
rd.lvm.lv=vg0/swap rhgb quiet nouveau.modeset=0
rd.driver.blacklist=nouveau plymouth.ignore-udev LANG=en_US.UTF-8
Build Date: 05 August 2017  06:19:43AM
Build ID: xorg-x11-server 1.19.3-11.el7
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.



We do not need all this information in the version output (yet), just
the version is sufficient, I guess.

Uli

**Comment by realsimix** [comment]
Hi Uli,

I've checked with Xnest - and of course it doesn't have the -version option :-)
No problem, I'll update...

Regards,
Simon

**Comment by realsimix** [comment]
I hope it's okay now:
[nx-libs-3.6.x-20180124-nxagent_version.patch.txt](https://github.com/ArcticaProject/nx-libs/files/1667339/nx-libs-3.6.x-20180124-nxagent_version.patch.txt)

**Comment by sunweaver** [comment]
Hi Simon,

On Friday, January 26, 2018, Simon Matter wrote:
> I hope it's okay now:
> nx-libs-3.6.x-20180124-nxagent_version.patch.txt 

I really think, we should get you into using PRs rather than attaching dozens patch variations to an open issue... Let me know if you are interested in a quick tutorial and I help you moving this bug into a PR.

Thanks+Greets
Mike

-- 
Sent from my Fairphone 2 (running Sailfish OS)
