### ISSUE TITLE
Weird 64bit brokenness comment

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#691]
In `hw/nxagent/Screen.c` we find this:
```
   1679     /* Assume that the mask fits in int... broken on Big Endian 64bit systems. */
   1680     Mask tmp_mask = attributes.event_mask;
   1681     nxagentGetDefaultEventMask(&tmp_mask);
   1682     attributes.event_mask = (int)tmp_mask;
```

There are two things I'd like to discuss here:

First, storing `attributes.event_mask` in line 1680 makes no sense to me since `nxagentGetDefaultEventMask()` will overwrite it.

Next:
`Mask` is `unsigned long` for 32bit and `CARD32` for 64bit (which is `unsigned int`; see `Xmd.h`)

`attributes` is `struct XSetWindowAttributes` and its member `event_mask` is always `long`.

That means:
   - in the 32bit case `tmp_mask` is `unsigned long`, we store a (signed) `long`, cast the result to (signed) `int` and store it in (signed) `long`
   - in the 64bit case `tmp_mask` is `unsigned int`, we store a (signed) `long`, cast the result to (signed) `int` and stored in (signed) `long`

According to C standard `int` is guaranteed to be at least 16bit, `long` is at least 32bit. According to `man XSetWindowAttributes` there are 15 attributes (= bits) defined, so even the the cast from `unsigned` to `signed` should not matter here.

Even on (64bit) Big Endian I don't see how there could be a problem. So what is this all about? Is the comment right at all? What am I missing?

**Comment by Ionic** [comment]
That's explained in the [commit message](https://github.com/ArcticaProject/nx-libs/commit/2d68caca72bd36b168b36b252c8035643c69e692).

The original problem was that `nxagentGetDefaultEventMask()` took a `Mask` pointer and wrote its magic into that location.

In X server context, `Mask` is always a 32 bit value (`CARD32`; hence `unsigned int` on 64 bit platforms and `unsigned long` on 32 bit platforms [since `long` is guaranteed to be at least 32 bits wide by the standard, while int is only guaranteed to be at least 16 bits wide]).

However, `struct XSetWindowAttributes.event_mask` is defined as `long`, as you correctly said.

On 32 bit platforms, that works out fine, since both locations are `long`-typed.

On 64 bit platforms, we now have a potential data size mismatch, since we're writing a 32 bit (`CARD32`) value into a potentially bigger memory space (`long`). At least on Linux with GCC, `long` is 64 bits wide in this case, so we've been populating only two 4 of 8 bytes in `event_mask`. That happened to work out fine on Little Endian platforms, where the least significant byte is laid out first (+ the high bytes left untouched/uninitialized), while on Big Endian platforms, the high bytes were set to the actual Mask with the low bytes left untouched/uninitialized.

I guess that this wasn't a huge deal on LE platforms since the other code mostly ignores the high bytes, while the low bytes are the really important data.

In retrospect, I'm not sure why I used an `int` cast there, it probably should have been a `Mask` cast in all these locations. Or just not any cast at all, since the temporary variable already is `Mask`-typed...

**Comment by uli42** [comment]
Are you really sure this isn't over-engineered? I mean, in the current code I have a value of some type A and write that value to a location of another type B. I'd say the compiler is supposed to implicitely cast the value to type B. The endianess should not matter here. 

I agree that there was a problem with the previous code, but wouldn't it have been easier (and clearer) to change `nxagentGetDefaultEventMask()` to not write to some pointer but return the Mask directly?

**Comment by Ionic** [comment]
Yeah, the issue was really a consequence of using a pointer as an output parameter and casting a memory location around to a different type.

By having `nxagentGetDefaultEventMask()` and `nxagentGetEventMask()` return `Mask` values directly and assigning them that shouldn't come up any longer.

Back then, I didn't want to change internals too much, but since this is strictly an NX addition, maybe it would have been better this way.
