### ISSUE TITLE
Review reconnection policies

### ISSUE THREAD

**Issue by nitomartinez** [ArcticaProject/nx-libs#73]
Review if the reconnection policy can be enhanced to support reconnection with:
- Different depths (migration between 32 bpp and 24 bpp seems to be possible)
- Different rendering versions....

See https://www.nomachine.com/AR03C00166

**Comment by sunweaver** [comment]
I presume that this can be considered as fixed by https://github.com/ArcticaProject/nx-libs/commit/443b52723e9d790e3a619406bcd8b0dd32390dc3.

Notes:
- from the provided doc URL, it only matters if the client-side Xserver has Render support or not. This has not been addressed so far and I see it as non-critical, because most Xservers nowadays have Render support on by default.
- The color depths issues during reconnect have been fixed by the above merge (PR #183). See also #132.
