### ISSUE TITLE
Color issue with some programs

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/nx-libs#79]
Submitted against X2Go BTS:
http://bugs.x2go.org/cgi-bin/bugreport.cgi?bug=262

Hello,

We are trying to move from NX to X2Go.

One of our tools is called Questa Sim (EDA tool from Mentor Graphics).

When we used to run it from NX, no issues.

When we use it with X2Go, we have color issues:

·         What was white or yellow text on a black background, now shows as
… black text on a black background, hence not readable.

·         While we can change colors in a preferences menu, unlike in NX,
changing the text color in X2Go environment does not work

Below are two screenshots:

·         One from NX, where yellow bar and text is readable

·         One from X2Go, where this bar and text have become black (on
black background)

Thanks,
- Edouard

**Comment by sunweaver** [comment]
@uli42: @Ionic: @vatral: @mbecroft: @opoplawski: does anyone know about other issues with nxagent, where colors are incorrectly displayed? Ideally a FLOSS software. I hear such issues here and there, but mostly with proprietary products as X clients.

**Comment by uli42** [comment]
There was an x2go issue only last week which turned out to being caused by a broken System setup. But I am not aware of any other color issues.

Vom Smartphone gesendet.

----- Ursprüngliche Nachricht -----
Von: "Mike Gabriel" <notifications@github.com>
Gesendet: ‎05.‎02.‎2017 22:58
An: "ArcticaProject/nx-libs" <nx-libs@noreply.github.com>
Cc: "Ulrich Sibiller" <uli42@gmx.de>; "Mention" <mention@noreply.github.com>
Betreff: Re: [ArcticaProject/nx-libs] Color issue with some programs (#79)

@uli42: @Ionic: @vatral: @mbecroft: @opoplawski: does anyone know about other issues with nxagent, where colors are incorrectly displayed? Ideally a FLOSS software. I hear such issues here and there, but mostly with proprietary products as X clients.

**Comment by mbecroft** [comment]
I have occasionally had similar color issues on NX and possibly also X2go (I think it's an nxagent issue). But it's infrequent and in my experience has only affected minor things like a border color so wasn't worth investigating. Don't know if same or different issue. Mine was definitely not a config issue but a problem with nxagent. Vague, and not a lot of help, I know.

It may turn out to be a simple config error as uli42 commented. You could set everything up from scratch on a clean system to verify the problem is still there. If that doesn't help, then:

Since this is proprietary software so you can't just look at the source code, and the vendor almost certainly doesn't certify it to work over X2go, I'd capture and visualize the X protocol data around the time of the problem in wireshark, in both the working and fault conditions. You might also capture the X protocol traffic client->nxagent and nxagent->your X server. You might be able to narrow down what's going on. (I'm assuming here you are using nxagent, not just nx protocol compression; if not, adjust above approach accordingly.) You can then use gdb on nxagent to track down where it is going wrong.

Another telling thing would be run x11vnc in your nxagent session and see if the colors are right or wrong. This would establish whether the issue arises in the X client/nxagent X server itself, or at the point where nxagent draws to your workstation/thinclient X server viia nxsshh/nxcomp (or the x2go equivalent of those).

If I carried out the above, my estimate would be 1 to 2 days to find and resolve the problem.

HTH

**Comment by sunweaver** [comment]
On  Mo 06 Feb 2017 00:06:41 CET, Mario Becroft wrote:

> I have occasionally had similar color issues on NX and possibly also  
> X2go (I tink it's an nxagent issue). But it's infrequent and in my  
> experience has only affected minor things like a border color so  
> wasn't really worth bothering to investigate. Don't know if same or  
> different issue. Mine was definitely not a config issue but a  
> problem with nxagent. Vague, and not a lot of help, I know.

Thanks for your feedback. One issue I noticed today, is this:
https://github.com/ArcticaProject/nx-libs/pull/315

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by opoplawski** [comment]
I don't know of any myself.

**Comment by uli42** [comment]
Meanwhile we have integrated the rgb file, so I am wondering if this is still happening with current beta releases.

**Comment by sunweaver** [comment]
We have know good means to verify / check on this issue anyway, as we don't have software that shows the issue inside nxagent sessions.

Thus, closing. People may re-open, if they can provide us with a proper test case.
