### ISSUE TITLE
Xlib: extension "MIT-SCREEN-SAVER" missing on display [Debian Jessie/KDE4]

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/nx-libs#80]
Reported via X2Go BTS:

Package: x2goagent
Version: 2:3.5.0.32-0x2go1+git20150704.734+jessie.main.1

Operating System: Debian Jessie 8.2
Kernel: #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09)
Desktop Environment: KDE4

The KDE Screen Locker does not launch automatically
when my session is controlled by x2goagent.  I am able
to lock the screen manually using "Lock" within the
KDE Menu and I can also lock the screen manually with
the use of either of the following commands:

/usr/lib/kde4/libexec/kscreenlocker_greet --immediateLock
/usr/bin/qbdus org.freedesktop.ScreenSaver /ScreenSaver Lock

However, if the screen lock is set to activate automatically,
it never does.  For example, if the KDE Screen Locker is
set to "Start Automatically After 1 minute", the screen lock
never activates even after the screen stays completely idle
for several minutes.

If I login to a KDE session directly on the system console,
the screen lock will activate after one minute.  If I login
to a KDE session using "xrdp", the screen lock will activate
after one minute.  If I login to a KDE session using X2GO,
screen lock never activates.

Within the ~/.xsession-x2go-errors file, several of the
following messages are logged:

Xlib:  extension "MIT-SCREEN-SAVER" missing on display ":50".

Someone from a KDE Forum suggests that the missing "MIT-SCREEN-SAVER"
extension would cause the issue of not having the screen lock
automatically.

Maybe I am missing a package or system library?  Is there a
modification that I can apply to the "/etc/x2go/x2goagent.options"
file that will correct the missing "MIT-SCREEN-SAVER" extension
issue?  Is there some other way that I can correct this problem
without having to try to build/compile from source?

There has been reference to similar problems in the past, but I have
not been able to locate a proper fix:

http://lists.x2go.org/pipermail/x2go-dev/2010-June/000579.html

I am able to duplicate this on two separate X2GO Servers (running
on Debian Jessie).  I know there has to be other Debian/X2GO/KDE4
users - do they not have this problem as well?

NOTE: I am able to set automatic screen lock if I switch to xscreensaver,
but if this is an bug with X2GO and KDE4, I am hoping that there is
a fix.  If needed, I can file a bug report with the KDE developers.
I am looking here first since this issue has only occurred within
my X2GO sessions.

Any help would be most appreciated.

Thank you.

**Comment by uli42** [comment]
IIRC the nomachine changelog contains hints why the SCREENSAVER extension had been deaktivated.

Vom Smartphone gesendet.

----- Ursprüngliche Nachricht -----
Von: "Mike Gabriel" notifications@github.com
Gesendet: ‎22.‎02.‎2016 16:46
An: "ArcticaProject/nx-libs" nx-libs@noreply.github.com
Betreff: [nx-libs] Xlib: extension "MIT-SCREEN-SAVER" missing on display[Debian Jessie/KDE4](#80)

Reported via X2Go BTS:
Package: x2goagent
Version: 2:3.5.0.32-0x2go1+git20150704.734+jessie.main.1
Operating System: Debian Jessie 8.2
Kernel: #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09)
Desktop Environment: KDE4
The KDE Screen Locker does not launch automatically
when my session is controlled by x2goagent. I am able
to lock the screen manually using "Lock" within the
KDE Menu and I can also lock the screen manually with
the use of either of the following commands:
/usr/lib/kde4/libexec/kscreenlocker_greet --immediateLock
/usr/bin/qbdus org.freedesktop.ScreenSaver /ScreenSaver Lock
However, if the screen lock is set to activate automatically,
it never does. For example, if the KDE Screen Locker is
set to "Start Automatically After 1 minute", the screen lock
never activates even after the screen stays completely idle
for several minutes.
If I login to a KDE session directly on the system console,
the screen lock will activate after one minute. If I login
to a KDE session using "xrdp", the screen lock will activate
after one minute. If I login to a KDE session using X2GO,
screen lock never activates.
Within the ~/.xsession-x2go-errors file, several of the
following messages are logged:
Xlib: extension "MIT-SCREEN-SAVER" missing on display ":50".
Someone from a KDE Forum suggests that the missing "MIT-SCREEN-SAVER"
extension would cause the issue of not having the screen lock
automatically.
Maybe I am missing a package or system library? Is there a
modification that I can apply to the "/etc/x2go/x2goagent.options"
file that will correct the missing "MIT-SCREEN-SAVER" extension
issue? Is there some other way that I can correct this problem
without having to try to build/compile from source?
There has been reference to similar problems in the past, but I have
not been able to locate a proper fix:
http://lists.x2go.org/pipermail/x2go-dev/2010-June/000579.html
I am able to duplicate this on two separate X2GO Servers (running
on Debian Jessie). I know there has to be other Debian/X2GO/KDE4
users - do they not have this problem as well?
NOTE: I am able to set automatic screen lock if I switch to xscreensaver,
but if this is an bug with X2GO and KDE4, I am hoping that there is
a fix. If needed, I can file a bug report with the KDE developers.
I am looking here first since this issue has only occurred within
my X2GO sessions.
Any help would be most appreciated.
Thank you.

**Comment by uli42** [comment]
I have not found much in in the changelogs. 

It seems to me that it has never been integrated. 

Using `xset` you can control the plain X11 screensaver. but I failed to force any screenblanking using those. This needs some investigation. The MIT-SCREEN-SAVER adds stuff on top of that but blanking should also work without the extension.
