### ISSUE TITLE
x2go: cannot connect to suspended session

### ISSUE THREAD

**Issue by Mc-Pain** [ArcticaProject/nx-libs#843]
How to reproduce:
1) Create a new session
2) Suspend it by "pause" key in x2goclient
3) Try to resume it
4) See screenshot

![изображение](https://user-images.githubusercontent.com/9453287/64846262-ea4b3c80-d614-11e9-9c96-1e870ed786da.png)

I'm blaming nx-libs because nxagent is handling its own SIGHUP by reconnecting the agent.

[session.log.gz](https://github.com/ArcticaProject/nx-libs/files/3608969/session.log.gz)

**Comment by Mc-Pain** [comment]
Reproducible on both 3.5.0.31 and 3.5.99.22 versions
OS: ALT Linux

**Comment by uli42** [comment]
On Fri, Sep 13, 2019 at 9:58 AM Mc-Pain <notifications@github.com> wrote:

> Reproducible on both 3.5.0.31 and 3.5.99.22 versions
> OS: ALT Linux
>

Well, I have taken a look at the session log. It seems you have compiled
Display.c with activated debugging. Is that on purpose?

Second, I am not aware of nxagent sending a SIGHUP to itself at any time.
nxagent suspends or resumes on reception of a SIGHUP which is normally sent
by x2go.

After reception of the SIGHUP we see this in your log:

Session: Resuming session at 'Fri Sep 13 13:34:06 2019'.
nxagentDisconnectSession: Disconnecting session with state
[SESSION_GOING_UP].
nxagentDisconnectSession: Disconnecting the X display.
nxagentWaitDisplay: Going to shutdown the X connection [3].
nxagentWaitDisplay: Going to wait for the NX transport.
nxagentWaitDisplay: The NX transport is not running.
nxagentResetSignalHandlers: Resetting the agent the signal handlers.
nxagentDisconnectSession: Disconnecting all X resources.
nxagentDisconnectSession: Disconnection completed. SigHup is [0]. IoError
is [0].
nxagentReconnect: changing nxagentKeyboard from [null/null] to [clone].
nxagentInstallSignalHandlers: Installing the agent signal handlers.
nxagentRemoveXConnection: Removing the X connection [3] from the device set.
nxagentInstallDisplayHandlers: Installing the error function predicate.
nxagentInternalOpenDisplay: Going to open the display
[nx/nx,options=/tmp/.x2go-test/C-test-50-1568370794_stDMATE_dp24/options:50].
nxagentDisplayWriteHandler: WRITE! Called with [0] bytes written.
Info: Proxy running in client mode with pid '2043'.
Info: Using errors file
'/tmp/.x2go-test/C-test-50-1568370794_stDMATE_dp24/session.log'.
Info: Using stats file
'/tmp/.x2go-test/C-test-50-1568370794_stDMATE_dp24/C-test-50-1568370794_stDMATE_dp24/stats'.
Loop: WARNING! Unrecognized session type 'unix-kde-depth_24'. Assuming
agent session.
Warning: Unrecognized session type 'unix-kde-depth_24'. Assuming agent
session.
Info: Waiting for connection from 'localhost' on socket 'tcp:*:41633'.
Info: Aborting the procedure due to signal '1'.
nxagentDisplayErrorPredicate: CHECK! Error is [1] with [0][0][2][0][0].
nxagentIOErrorHandler: Got I/O error with nxagentException.ioError [0].
nxagentIOErrorHandler: Set nxagentException.ioError to [1].
nxagentInternalOpenDisplay: Setting the NX flush policy to immediate.
nxagentInternalOpenDisplay: Function returned display at [(nil)].
nxagentPostInstallSignalHandlers: Dealing with the proxy signal handlers.
nxagentReconnectSession: WARNING! Failed display reconnection.
<<<<<<<<<<<<<<<<<<<<
nxagentReconnectSession: Reconnection failed in display step. Restoring
options. <<<<<<<<<<<<<<<<<<<<<
nxagentReconnectSession: Reconnection failed with reason 'Couldn't open the
display.' <<<<<<<<<<<<<<<<<<
nxagentReconnectSession: Cannot launch the dialog without a valid display.
<<<<<<<<<<<<<<<
Session: Display failure detected at 'Fri Sep 13 13:35:06 2019'.
Session: Suspending session at 'Fri Sep 13 13:35:06 2019'.

So there seems to be a problem in accessing your clientside X-Server. Are
you reconnecting from the same machine as before? Can you please post the
content of /tmp/.x2go-test/C-test-50-*_stDMATE_dp24/options?

Uli

**Comment by uli42** [comment]
no answer received for almost 16 months - closing
