### ISSUE TITLE
Check etersoft commits

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#874]
https://gitlab.eterfund.ru/dimbor/nx-libs/commits/dev2

There's a clipboard fix, some motif stuff (?), some locale stuff and channel stuff (separate issue for that: #873)

**Comment by uli42** [comment]
@dimbor_ru: can you tell us more about those motif changes?

**Comment by dimbor-ru** [comment]
About motif&locale. This old patch is not worthy of your attention at least for two reasons:
1) The first versions of wine (on server side) and nxwin (on client) could not boast of strict adherence to ICCCM. These facts gave me a reason to bully in relation to them "for a specific task".
2) This hack is also because it was time-consuming and too lazy to organize the conversion of nxwin window titles under cygwin. ;)
The patch is present in my repo only for backward compatibility purposes. And its impact on other applications is unpredictable.

**Comment by uli42** [comment]
Thanks for the clarification. So it boils down to the clipboard patch, which essentially matches one of the FIXMEs I have introduced. So I will extend the existing code rather than using your patch (which drops all the comments).

**Comment by dimbor-ru** [comment]
Ok. Sorry for being careless with your code. I had a hole and I had to shut it up quickly. Naturally, this is a draft. I offered only #873, the rest you yourself have found from my repo ;)

**Comment by uli42** [comment]
I have now written a patch based on your clipboard changes and added some more targets, see #875
