### ISSUE TITLE
Mouse unusable with nxagent (~3.5.99.24 and later)

### ISSUE THREAD

**Issue by realsimix** [ArcticaProject/nx-libs#983]
My test setup was broken because of a dead motherboard. After quite some time I was now able to fix it and did tests with recent versions of nx-libs.

I've discovered a strange issue where the mouse is unusable. Mouse movement works but it seems like mouse buttons are mixed up somehow and mouse clicks don't work.

I've tested with some snapshots I had on disk:
nxagent 20200630 OK
nxagent 20201022 BROKEN
nxagent 20201105 BROKEN
nxagent 20210109 BROKEN

Does anybody remember changes which could result in such issues?

Thanks,
Simon

**Comment by uli42** [comment]
Hmm, I am not aware. Am I right that you can reliably trigger that?

**Comment by realsimix** [comment]
Correct, nxproxy version doesn't matter but nxagent does.
I start an XFCE session and mouse is not usable, it moves but keys don't work as expected and desktop can not be used.

nxproxy is latest from git
nxagent from 20200630 works
nxagent from 20201022 and later are broken

Just discovered something interesting:
This happens with `nxagent -geometry fullscreen`. As soon as I switch to window mode with Alt&F, it works. Then switching back to fullscreen again with Alt&F keeps the session working.

**Comment by uli42** [comment]
I will try to trigger this this evening.

3.5.99.24 was released on May 31st
3.5.99.25 was released on Nov. 4th

So what are the dates you are mentioning related to?

Here are the merges we had in your time frame:

*   13211ec 2020-10-18 | Merge branch 'uli42-pr/window_resize_bug'
into 3.6.x [Mike Gabriel]
*   7a02b4a 2020-10-17 | Merge branch 'uli42-pr/fix_stack_smashing'
into 3.6.x [Mike Gabriel]
*   2b0976e 2020-10-17 | Merge branch 'uli42-pr/fix_caps_handling'
into 3.6.x [Mike Gabriel]
*   05cb09a 2020-10-17 | Merge branch 'uli42-pr/libNX_X11_defines'
into 3.6.x [Mike Gabriel]
*   X d121f2a 2020-10-17 | Merge branch 'uli42-pr/nxdialog_rpm' into
3.6.x [Mike Gabriel]
*   X 6857e26 2020-10-17 | Merge branch 'mjtrangoni-fix-pvs-ci' into
3.6.x [Mike Gabriel]
*   bc68b4a 2020-10-17 | Merge branch 'uli42-pr/fix_wrap_macros' into
3.6.x [Mike Gabriel]
*   X e103024 2020-06-29 | Merge branch 'mjtrangoni-add-pvs-studio'
into 3.6.x [Mike Gabriel]

The merges marked with X are probably not causing this because they
are changing stuff outside of nxagent. The only keyboard related
change is  2b0976e. So maybe you can track this down by leaving out
one or another.

Uli

**Comment by realsimix** [comment]
For building RPMs I'm often using patches directly from github like this:
This is the commit:
https://github.com/ArcticaProject/nx-libs/commit/13211ec6a5060db75c93cbb4e75d017b0a49386e

I get the patch like so:
https://github.com/ArcticaProject/nx-libs/commit/13211ec6a5060db75c93cbb4e75d017b0a49386e.patch

Now I'm really confused as both links above don't show the same changes! Maybe it's just lack of coffee or something but I just confused why this happens?

I think that's what I always did when backporting fixes into RPM packages...

**Comment by realsimix** [comment]
But this works:
https://github.com/ArcticaProject/nx-libs/commit/13211ec6a5060db75c93cbb4e75d017b0a49386e.diff

Can someone confirm these files are different
https://github.com/ArcticaProject/nx-libs/commit/13211ec6a5060db75c93cbb4e75d017b0a49386e.patch
https://github.com/ArcticaProject/nx-libs/commit/13211ec6a5060db75c93cbb4e75d017b0a49386e.diff

**Comment by uli42** [comment]
After a quick glance I think you are confused by the different order of the
changes. The diff has all changes "in one go" while the patch sorts them by
single commits.

Uli

**Comment by realsimix** [comment]
Looks like https://github.com/ArcticaProject/nx-libs/commit/0f8ed4d103b3f68d5cedaa611b47b7cdb1e0517c is the culprit.

Any ideas?

**Comment by uli42** [comment]
ok, then I will undo it. Or better add an explaining comment.

**Comment by realsimix** [comment]
Thanks, I can confirm that this resolves the issue.

**Comment by uli42** [comment]
I cannot seem to replicate the issue. Can you please provide detailed
instructions?

**Comment by realsimix** [comment]
> I cannot seem to replicate the issue. Can you please provide detailed
> instructions?
>

There is nothing special. Nxproxy on a client connects to nxagent on
server. Nxagent is run with -geometry fullscreen and runs startxfce
desktop.

**Comment by uli42** [comment]
Ok, with a slightly modified version of
testscripts/run-nxproxy2nxagent-on-localhost I was able to replicate
the issue. However, I cannot simply fix it because unfortunately that
single change was a fix for another issue (#925)...

diff --git a/testscripts/run-nxproxy2nxagent-on-localhost
b/testscripts/run-nxproxy2nxagent-on-localhost
index d520a4c..5696741 100755
--- a/testscripts/run-nxproxy2nxagent-on-localhost
+++ b/testscripts/run-nxproxy2nxagent-on-localhost
@@ -30,7 +30,8 @@
ulimit -c "unlimited"

NXPROXYBIN="nxproxy"
-NXAGENTBIN="nxagent"
+#NXAGENTBIN="nxagent"
+NXAGENTBIN="/home/uli/work/nx/ArcticaProject/nx-libs/nx-X11/programs/Xserver/nxagent"



@@ -108,7 +109,7 @@ export DISPLAY
#valgrind -v --num-callers=8 --error-limit=no --trace-children=no \
#valgrind --num-callers=8 --tool=memcheck --leak-check=yes
--show-reachable=yes --track-fds=yes \
#ldd "${NXAGENTBIN}"
-"${NXAGENTBIN}" -name 'NX' -geometry "800x600+100+100" "${@}" \
+"${NXAGENTBIN}" -name 'NX' -geometry "fullscreen" "${@}" \
"${NX_AGENT}" 2>>"${NX_ROOT}/C-${NX_PORT}/session" &

#
@@ -141,3 +142,5 @@ echo "Running the X server side NX proxy."
2>>"${NX_ROOT}/S-${NX_PORT}/session" &

echo "Session running on display :$NX_PORT."
+
+xterm -display $(hostname):9

**Comment by uli42** [comment]
Found the root cause and added a better fix than reverting an old commit.

**Comment by realsimix** [comment]
Thanks, I can confirm that the patch fixes the issue.

**Comment by realsimix** [comment]
Does it make sense to leave this open until the patch goes in?

**Comment by uli42** [comment]
yes, that's how we handle that usually.
